### PR TITLE
Ell18 mod/ pm-triggered update

### PR DESCRIPTION
**Pull request by kameyer226**
Adds offset to ellx config, but also modifies pm-triggered due to work done on the ell18_mod branch while it was open.  Please review

### CODE REVIEW

**Comment by ksunden** [comment]
Can this possibly wait until we have the trait to do exactly this? its just about ready just going through the final phases of review and filling out details.

**Comment by ksunden** [comment]
The implementation of the trait is done aside from some documentation and cleanup

See

yaq-project/yaq-traits#11

yaq-project/yaq-python#17

yaq-project/yeps#3

**Comment by kameyer226** [comment]
Not inclined to overhaul entire yaqd-thorlabs library to YEP 312, am using ell18 as tuning curve currently which requires the offset and no other methods/configs

**Review by ksunden — COMMENTED** [review]
it is a lesser change to use the trait, which does _exactly_ this in a standardized way by default... there is a reason we have the trait system and it is precisely for this usecase

**Comment by kameyer226** [comment]
Provide pseudocode to show how change would be easier, thanks

**Comment by ksunden** [comment]
Literally it would just be adding the new trait to the toml and that is it, no code changes

**Comment by ddkohler** [comment]
@kameyer226 technical minor difference between this implementation and has-transformed-position is your implementation stores the offset in config, while our trait stores the offset in state.  So one minor thing that you would need to adapt to.

Until we put the finishing touches on this trait, I would just continue to use this branch until we get the trait established, and then we can switch over.  I'm in the same holding pattern with yaqd-newport-conex-agp, where we need an offset.  

I think I'm the rate limiting step in implementation of the trait--I will get to it shortly.

**Comment by untzag** [comment]
I think this is obsolete, anyone can reopen if I'm wrong.

**Pull request closed without merging**
